version: '3.7'

services:
  server_app:
    container_name: fs2_ride_hailer_rails_app
    networks:
      - fs2_ride_hailer
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - './.env'
    volumes:
      - '.:/application'
    ports:
      - 3000:3000
    depends_on:
      - database
    entrypoint:
      - ./entry-point.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

  database:
    image: mdillon/postgis:10-alpine
    container_name: fs2_ride_hailer_db
    networks:
      - fs2_ride_hailer
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432

volumes:
  postgres: ~

networks:
  fs2_ride_hailer:
    name: fs2_ride_hailer